# Generated by Django 3.0.5 on 2021-04-23 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sii_Api',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_idApp', models.IntegerField(default='')),
                ('m_date', models.DateField()),
                ('m_type', models.CharField(default='', max_length=70)),
                ('m_valeur', models.CharField(default='', max_length=200)),
                ('m_alerte', models.BooleanField(default=False)),
                ('m_message', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
    ]
